name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest tests/

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images (api and ui)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/play-api -f Dockerfile.api .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/play-ui -f Dockerfile.ui .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/play-api
          docker push ${{ secrets.DOCKER_USERNAME }}/play-ui
